{{- if .Values.magnus.enabled }}
{{- with .Values.magnus }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-magnus" }}
{{- $magnusPortStart := printf "%s" (include "jumpserver.magnus.port.start" $) | int }}
{{- $magnusPortEnd := printf "%s" (include "jumpserver.magnus.port.end" $) | int}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    {{- range $port := untilStep $magnusPortStart $magnusPortEnd 1 }}
    - port: {{ $port }}
      {{- if eq $.Values.magnus.service.type "NodePort" }}
      nodePort: {{ $port }}
      {{- end }}
      targetPort: magnus-{{ $port }}
      protocol: TCP
      name: magnus-{{ $port }}
    {{- end }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- toYaml .labels | nindent 4 }}
{{- end }}
{{- end }}
