apiVersion: v1
appVersion: "v2.13.2"
description: A Helm chart for Deploying Jumpserver on Kubernetes
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://github.com/bitnami/charts/tree/master/bitnami/mysql
  version: 8.8.3
- condition: redis.enabled
  name: redis
  repository: https://github.com/bitnami/charts/tree/master/bitnami/redis
  version:  14.8.8
name: jumpserver
version: 0.1.0
