{{- if .Values.core.enabled }}
{{- with .Values.core }}
{{- $fullName := include "jumpserver.fullname" $ }}
{{- $containerName := "jms-core" }}
{{- $registryName := $.Values.global.imageRegistry | default .image.registry }}
{{- $mysqlPort := printf "%s" (include "jumpserver.magnus.mysql.port" $) }}
{{- $mariadbPort := printf "%s" (include "jumpserver.magnus.mariadb.port" $) }}
{{- $redisPort := printf "%s" (include "jumpserver.magnus.redis.port" $) }}
{{- $postgresqlPort := printf "%s" (include "jumpserver.magnus.postgresql.port" $) }}
{{- $oraclePorts := printf "%s" (include "jumpserver.magnus.oracle.ports" $) }}
{{- $imageName := $.Values.xpack.enabled | ternary "jumpserver/core-ee" "jumpserver/core-ce" }}
{{- $imageTag := "v3.10.0" }}
{{- $imageWithTag := printf "%s/%s:%s" $registryName $imageName $imageTag | quote }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-{{ $containerName }}"
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.global.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ $imageWithTag }}
          imagePullPolicy: {{ .image.pullPolicy | quote }}
          args: ["start", "web"]
          env:
            - name: CORE_HOST
              value: "http://{{ $fullName }}-jms-core:{{ $.Values.core.service.web.port }}"
            - name: SECRET_KEY
              value: {{ required "A valid secretKey is required!" .config.secretKey | quote }}
            - name: BOOTSTRAP_TOKEN
              value: {{ required "A valid bootstrapToken is required!" .config.bootstrapToken | quote }}
            - name: DEBUG
              value: {{ .config.debug | quote }}
            - name: LOG_LEVEL
              value: {{ .config.log.level | quote }}
            - name: HTTP_LISTEN_PORT
              value: {{ .service.web.port | quote }}
            - name: DB_ENGINE
              value: {{ include "jumpserver.database.engine" $ | quote }}
            - name: DB_HOST
              value: {{ include "jumpserver.database.host" $ | quote }}
            - name: DB_PORT
              value: {{ include "jumpserver.database.port" $ | quote }}
            - name: DB_USER
              value: {{ include "jumpserver.database.user" $ | quote }}
            - name: DB_PASSWORD
              value: {{ include "jumpserver.database.password" $ | quote }}
            - name: DB_NAME
              value: {{ include "jumpserver.database.database" $ | quote }}
            - name: REDIS_HOST
              value: {{ include "jumpserver.redis.host" $ | quote }}
            - name: REDIS_PORT
              value: {{ include "jumpserver.redis.port" $ | quote }}
            - name: REDIS_PASSWORD
              value: {{ include "jumpserver.redis.password" $ | quote }}
            - name: MAGNUS_MYSQL_PORT
              value: {{ $mysqlPort | quote }}
            - name: MAGNUS_MARIADB_PORT
              value: {{ $mariadbPort | quote }}
            - name: MAGNUS_REDIS_PORT
              value: {{ $redisPort | quote }}
            - name: MAGNUS_POSTGRESQL_PORT
              value: {{ $postgresqlPort | quote }}
            - name: MAGNUS_ORACLE_PORTS
              value: {{ $oraclePorts | quote }}
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: web
              containerPort: {{ .service.web.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/jumpserver/data"
              name: "jms-core-data"
              {{- if .persistence.subPath }}
              subPath: {{ .persistence.subPath | quote }}
              {{- end }}
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            {{- if .persistence.existingClaim }}
            claimName: {{ .persistence.existingClaim | quote }}
            {{- else }}
            claimName: '{{ $fullName }}-jms-core-data'
            {{- end }}
          name: "jms-core-data"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
