{{- if and .Values.xpack.enabled (not .Values.chen.persistence.existingClaim)}}
{{- with .Values.chen }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-chen-data" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
  {{- with .persistence.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .persistence.finalizers }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .persistence.size | quote }}
      {{- end }}
  storageClassName: {{ include "jumpserver.chen.storageClass" . }}
{{- end }}
