{{- if .Values.koko.enabled }}
{{- with .Values.koko }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-koko" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jumpserver.labels" $ | nindent 4 }}
    {{- toYaml .labels | nindent 4 }}
data:
{{- $path := printf "%s/%s/%s" "configs" "jms-koko" "config.yml" -}}
{{- tpl (($.Files.Glob $path ).AsConfig) $ | nindent 2 }}
{{- end }}
{{- end }}
