{{- if .Values.core.enabled }}
{{- with .Values.core }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-celery" }}
{{- $containerName := "jms-celery" }}
{{- $image := printf "%s:%s" .image.repository .image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.jumpserver.org/name: {{ $containerName }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{$image}}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .command }}
          command:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          args: ["start", "task"]
          env:
            - name: SECRET_KEY
              value: "{{ .config.secretKey }}"
            - name: BOOTSTRAP_TOKEN
              value: "{{ .config.bootstrapToken }}"
            - name: DEBUG
              value: "{{ .config.debug }}"
            - name: LOG_LEVEL
              value: "{{ .config.log.level }}"
            - name: SESSION_EXPIRE_AT_BROWSER_CLOSE
              value: "true"
            - name: HTTP_LISTEN_PORT
              value: "{{ .service.web.port }}"
            - name: WS_LISTEN_PORT
              value: "{{ .service.ws.port }}"
            - name: DB_ENGINE
              value: "{{ .config.db.engine }}"
            - name: DB_HOST
              value: "{{ .config.db.host }}"
            - name: DB_PORT
              value: "{{ .config.db.port }}"
            - name: DB_USER
              value: "{{ .config.db.user }}"
            - name: DB_PASSWORD
              value: "{{ .config.db.password }}"
            - name: DB_NAME
              value: "{{ .config.db.name }}"
            - name: REDIS_HOST
              value: "{{ .config.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .config.redis.port }}"
            - name: REDIS_PASSWORD
              value: "{{ .config.redis.password }}"
          {{- with .env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /opt/jumpserver/utils/check_celery.sh
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/jumpserver/config.yml"
              name: "jms-core-config"
              subPath: "config.yml"
            - mountPath: "/opt/jumpserver/data"
              name: "jms-core-data"
            - mountPath: "/opt/jumpserver/logs"
              name: "jms-core-logs"
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - configMap:
            name: '{{include "jumpserver.fullname" $}}-jms-core'
          name: "jms-core-config"
        - persistentVolumeClaim:
            claimName: '{{include "jumpserver.fullname" $}}-jms-core-data'
          name: "jms-core-data"
        - persistentVolumeClaim:
            claimName: '{{include "jumpserver.fullname" $}}-jms-core-logs'
          name: "jms-core-logs"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
