{{- if .Values.core.enabled }}
{{- with .Values.core }}
{{- $fullName := printf "%s-%s" (include "jumpserver.fullname" $) "jms-celery" }}
{{- $containerName := "jms-celery" }}
{{- $image := printf "%s:%s" .image.repository .image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.jumpserver.org/name: {{ $containerName }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jumpserver.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- toYaml .labels | nindent 8 }}
    spec:
      serviceAccountName: {{ template "jumpserver.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $containerName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{$image}}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .command }}
          command:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          args: ["start", "task"]
          env:
            - name: "DB_HOST"
              value: "{{.config.db.host}}"
            - name: "DB_PORT"
              value: "{{.config.db.port}}"
            - name: "REDIS_HOST"
              value: "{{.config.redis.host}}"
            - name: "REDIS_PORT"
              value: "{{.config.redis.port}}"
          {{- with .env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /opt/py3/bin/python /opt/jumpserver/apps/manage.py check_celery
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/jumpserver/config.yml"
              name: "jms-core-config"
              subPath: "config.yml"
            - mountPath: "/opt/jumpserver/data"
              name: "jms-core-data"
            - mountPath: "/opt/jumpserver/logs"
              name: "jms-core-logs"
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - configMap:
            name: '{{include "jumpserver.fullname" $}}-jms-core'
          name: "jms-core-config"
        - persistentVolumeClaim:
            claimName: '{{include "jumpserver.fullname" $}}-jms-core-data'
          name: "jms-core-data"
        - persistentVolumeClaim:
            claimName: '{{include "jumpserver.fullname" $}}-jms-core-logs'
          name: "jms-core-logs"
      {{- with .volumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
