# 项目名称, 会用来向Jumpserver注册, 识别而已, 不能重复
NAME: {{ printf "%s-%s" "jms-lion" (randAlphaNum 32 | b64enc) | trunc 31 | trimSuffix "-" }}

# Jumpserver项目的url, api请求注册会使用
CORE_HOST: http://{{include "jumpserver.fullname" $}}-jms-core:{{$.Values.core.service.web.port}}

# Bootstrap Token, 预共享秘钥, 用来注册使用的service account和terminal
# 请和jumpserver 配置文件中保持一致，注册完成后可以删除
BOOTSTRAP_TOKEN: {{ $.Values.core.config.bootstrapToken }}

# 启动时绑定的ip, 默认 0.0.0.0
BIND_HOST: 0.0.0.0

# 监听的HTTP/WS端口号，默认8081
HTTPD_PORT: {{ $.Values.lion.service.web.port }}

# 设置日志级别 [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
LOG_LEVEL: {{ $.Values.lion.config.log.level }}

# Guacamole Server ip， 默认127.0.0.1
# GUA_HOST: 127.0.0.1

# Guacamole Server 端口号，默认4822
# GUA_PORT: 4822

# 会话共享使用的类型 [local, redis], 默认local
SHARE_ROOM_TYPE: {{ $.Values.lion.config.share_room_type }}

# Redis配置
REDIS_HOST: {{ $.Values.core.config.redis.host }}
REDIS_PORT: {{ $.Values.core.config.redis.port }}
REDIS_PASSWORD: {{ $.Values.core.config.redis.password }}
# REDIS_DB_ROOM:
